---
- name: Launch GCP Instance via Jenkins
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # We will pass these variables from Jenkins
    gcp_project: "jenkins-terraform-480215"
    gcp_zone: "us-central1-a"
    machine_type: "e2-medium"
    instance_name: "jenkins-ansible-vm"
    # This variable reads the path of the secret file injected by Jenkins
    gcp_cred_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"

  tasks:
    - name: Create a GCP instance
      google.cloud.gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            source_image: projects/debian-cloud/global/images/family/debian-11
        network_interfaces:
          - network:
              selfLink: "global/networks/default"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: instance_data

    - name: Display Instance IP
      debug:
        msg: "Instance Created. Public IP: {{ instance_data.networkInterfaces[0].accessConfigs[0].natIP }}"
